/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package migracionbasededatos;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class Migracion extends javax.swing.JFrame {

    /**
     * Creates new form Migracion
     */
    private static Connection connectionsqlserver, connectionmysql;

    public Migracion() {
        initComponents();

        Migracion.getSQLSERVERConnection();
        System.out.println("sqlserver conectada");
        Migracion.getMysqlConnection();
        System.out.println("mysql conectada");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_instanciaOrigen = new javax.swing.JTextField();
        tf_baseDatosOrigen = new javax.swing.JTextField();
        tf_puertoOrigen = new javax.swing.JTextField();
        tf_usuarioOrigen = new javax.swing.JTextField();
        pf_passwordOrigen = new javax.swing.JPasswordField();
        btn_probarOrigen = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_instanciaDestino = new javax.swing.JTextField();
        tf_baseDatosDestino = new javax.swing.JTextField();
        tf_puertoDestino = new javax.swing.JTextField();
        tf_usuarioDestino = new javax.swing.JTextField();
        pf_passwordDestino = new javax.swing.JPasswordField();
        btn_probarDestino = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_desReplicar = new javax.swing.JButton();
        btn_Replicar = new javax.swing.JButton();
        btn_Guardar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        cb_LaptopSERVER = new javax.swing.JCheckBox();
        cb_PCSERVER = new javax.swing.JCheckBox();
        cb_laptopMYSQL = new javax.swing.JCheckBox();
        cb_PCMYSQL = new javax.swing.JCheckBox();
        cb_printerMYSQL = new javax.swing.JCheckBox();
        cb_productMYSQL = new javax.swing.JCheckBox();
        cb_printerSERVER = new javax.swing.JCheckBox();
        cb_productSERVER = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTabbedPane3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("BASE DE DATOS ORIGEN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("NOMBRE DE INSTANCIA");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("NOMBRE DE BASE DE DATOS");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("PUERTO");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("NOMBRE DE USUARIO");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("PASSWORD");

        tf_instanciaOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_instanciaOrigenActionPerformed(evt);
            }
        });

        btn_probarOrigen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_probarOrigen.setText("Probar");
        btn_probarOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_probarOrigenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btn_probarOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(95, 95, 95))
                                .addComponent(tf_usuarioOrigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pf_passwordOrigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_puertoOrigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_baseDatosOrigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_instanciaOrigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(63, 63, 63))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(105, 105, 105))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(50, 50, 50))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(62, 62, 62)))
                            .addComponent(jLabel1))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_instanciaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_baseDatosOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_puertoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_usuarioOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_passwordOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(btn_probarOrigen)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("SQL SERVER", jPanel4);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("BASE DE DATOS DESTINO");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("NOMBRE DE INSTANCIA");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("NOMBRE DE BASE DE DATOS");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("PUERTO");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("NOMBRE DE USUARIO");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("PASSWORD");

        btn_probarDestino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_probarDestino.setText("Probar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(btn_probarDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel12))
                            .addComponent(tf_usuarioDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pf_passwordDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_puertoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_baseDatosDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_instanciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel11))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel10))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel9))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel8)))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_instanciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_baseDatosDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_puertoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_usuarioDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pf_passwordDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_probarDestino)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("MYSQL", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jTabbedPane3))
        );

        jTabbedPane2.addTab("CONEXIONES", jPanel2);

        jTabbedPane4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("SQL SERVER");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("MYSQL");

        btn_desReplicar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_desReplicar.setText("<<<");

        btn_Replicar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Replicar.setText(">>>");

        btn_Guardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Guardar.setText("Guardar");

        btn_Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Cancelar.setText("Cancelar");

        cb_LaptopSERVER.setText("Laptop");

        cb_PCSERVER.setText("PC");

        cb_laptopMYSQL.setText("Laptop");

        cb_PCMYSQL.setText("PC");

        cb_printerMYSQL.setText("Printer");

        cb_productMYSQL.setText("Product");

        cb_printerSERVER.setText("Printer");

        cb_productSERVER.setText("Product");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cb_LaptopSERVER)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_laptopMYSQL)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cb_productSERVER)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cb_printerSERVER)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                                        .addComponent(btn_desReplicar))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cb_PCSERVER)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_Replicar)))
                                .addGap(98, 98, 98)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_printerMYSQL)
                            .addComponent(cb_PCMYSQL)
                            .addComponent(cb_productMYSQL))
                        .addGap(99, 99, 99))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btn_Guardar)
                .addGap(125, 125, 125)
                .addComponent(btn_Cancelar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_LaptopSERVER)
                    .addComponent(cb_laptopMYSQL))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_PCSERVER)
                    .addComponent(cb_PCMYSQL)
                    .addComponent(btn_Replicar))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_printerMYSQL)
                    .addComponent(cb_printerSERVER)
                    .addComponent(btn_desReplicar))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_productMYSQL)
                    .addComponent(cb_productSERVER))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Guardar)
                    .addComponent(btn_Cancelar))
                .addGap(85, 85, 85))
        );

        jTabbedPane4.addTab("REPLICAR TABLAS", jPanel3);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("SQL SERVER");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("MYSQL");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(254, 254, 254))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel15)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("BITACORA", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );

        jTabbedPane2.addTab("TABLAS", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_instanciaOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_instanciaOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_instanciaOrigenActionPerformed

    private void btn_probarOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_probarOrigenActionPerformed

    }//GEN-LAST:event_btn_probarOrigenActionPerformed

    public static void RevisarBitacora(String nombreTabla) {
        int copiado_l;
        String nombretabla_l, valores_l, nombretable_l, operaciones_l;
        Statement stmt1, stmt2;
        try {
            stmt1 = connectionsqlserver.createStatement();
            ResultSet rsSQL1 = stmt1.executeQuery("select * from bitacora where nombretabla=" + nombreTabla);
            copiado_l = rsSQL1.getInt("Copiado");
            nombretabla_l = rsSQL1.getString("NombreTabla");
            valores_l = rsSQL1.getString("Valores");
            operaciones_l = rsSQL1.getString("Operacion");
            ActuaizarDatos(copiado_l, nombreTabla, valores_l, operaciones_l, nombreTabla);
        } catch (Exception e) {
        }
    }

    public static void ActuaizarDatos(int copiada, String nombretabla, String valores, String operaciones, String nombretable) {
        Object datosentrada[] = new Object[100];
        System.out.println(operaciones.toString());
        try {
            Statement stmt2 = connectionmysql.createStatement();
            Statement stmt1 = connectionsqlserver.createStatement();
            Statement stmt3 = connectionsqlserver.createStatement();

            if (copiada == 0 && (operaciones.equals("insert") || operaciones.equals("update"))) {
                if (nombretable.equals("Laptop")) {
                    ResultSet rsSQL2 = stmt1.executeQuery("select * from dbo.Laptop where code=" + valores);
                    while (rsSQL2.next()) {
                        datosentrada[0] = rsSQL2.getInt("code");
                        System.out.println(datosentrada[0]);
                        datosentrada[1] = rsSQL2.getString("model");
                        System.out.println(datosentrada[1]);
                        datosentrada[2] = rsSQL2.getInt("speed");
                        System.out.println(datosentrada[2]);
                        datosentrada[3] = rsSQL2.getInt("ram");
                        System.out.println(datosentrada[3]);
                        datosentrada[4] = rsSQL2.getInt("hd");
                        System.out.println(datosentrada[4]);
                        datosentrada[5] = rsSQL2.getDouble("price");
                        System.out.println(datosentrada[5]);
                        datosentrada[6] = rsSQL2.getInt("screen");
                        System.out.println(datosentrada[6]);
                        if (operaciones.equals("insert")) {
                            stmt2.executeUpdate("insert into laptop(code,model,speed,ram,hd,price,screen) values( '" + datosentrada[0] + "','"
                                    + datosentrada[1] + "','" + datosentrada[2] + "','" + datosentrada[3] + "','"
                                    + datosentrada[4] + "','" + datosentrada[5] + "','" + datosentrada[6] + "');");
                        } else if (operaciones.equals("update")) {
                            stmt2.executeUpdate("update laptop set model='" + datosentrada[1] + "' where code=" + datosentrada[0] + " ");
                        }
                        stmt3.execute("update bitacora set copiado=1 where nombretabla=" + nombretabla);
                    }
                } else if (nombretable.equals("PC")) {
                    ResultSet rsSQL2 = stmt1.executeQuery("select * from PC where code =" + valores);
                    while (rsSQL2.next()) {
                        datosentrada[0] = rsSQL2.getInt("code");
                        datosentrada[1] = rsSQL2.getString("model");
                        System.out.println(datosentrada[1]);
                        datosentrada[2] = rsSQL2.getInt("speed");
                        System.out.println(datosentrada[2]);
                        datosentrada[3] = rsSQL2.getInt("ram");
                        System.out.println(datosentrada[3]);
                        datosentrada[4] = rsSQL2.getInt("hd");
                        System.out.println(datosentrada[4]);
                        datosentrada[5] = rsSQL2.getString("cd");
                        System.out.println(datosentrada[5]);
                        datosentrada[6] = rsSQL2.getDouble("price");
                        System.out.println(datosentrada[6]);
                        stmt2.executeUpdate("insert into PC(code,model,speed,ram,hd,cd,price) values('" + datosentrada[0] + "','"
                                + datosentrada[1] + "','" + datosentrada[2] + "','" + datosentrada[3] + "','"
                                + datosentrada[4] + "','" + datosentrada[5] + "','" + datosentrada[6] + "');");
                        stmt3.execute("update bitacora set copiado=1 where nombretabla=" + valores);
                    }
                } else if (nombretable.equals("Printer")) {
                    ResultSet rsSQL2 = stmt1.executeQuery("select * from Printer where code=" + valores);
                    while (rsSQL2.next()) {
                        datosentrada[0] = rsSQL2.getInt("code");
                        System.out.println(datosentrada[0]);
                        datosentrada[1] = rsSQL2.getString("model");
                        System.out.println(datosentrada[1]);
                        datosentrada[2] = rsSQL2.getString("color");
                        System.out.println(datosentrada[2]);
                        datosentrada[3] = rsSQL2.getString("type");
                        System.out.println(datosentrada[3]);
                        datosentrada[4] = rsSQL2.getDouble("price");
                        System.out.println(datosentrada[4]);
                        stmt2.executeUpdate("insert into Printer(code,model,color,type,price) values('" + datosentrada[0] + "','"
                                + datosentrada[1] + "','" + datosentrada[2] + "','" + datosentrada[3] + "','"
                                + datosentrada[4] + "');");
                        stmt3.execute("update bitacora set copiado=1 where nombretabla=" + valores);
                    }
                } else if (nombretable.equals("Product")) {
                    ResultSet rsSQL2 = stmt1.executeQuery("select * from Printer where model=" + valores);
                    while (rsSQL2.next()) {
                        datosentrada[0] = rsSQL2.getString("maker");
                        System.out.println(datosentrada[0]);
                        datosentrada[1] = rsSQL2.getString("model");
                        System.out.println(datosentrada[1]);
                        datosentrada[2] = rsSQL2.getString("type");
                        System.out.println(datosentrada[2]);
                        stmt2.executeUpdate("insert into Product(maker,model,type) values('" + datosentrada[0] + "','"
                                + datosentrada[1] + "','" + datosentrada[2] + "');");
                        stmt3.execute("update bitacora set copiado=1 wher nombretabla=" + valores);
                    }
                } else if (copiada == 0 && operaciones.equals("delete")) {
                    if (nombretable.equals("Laptop")) {
                        stmt2.executeUpdate("SET FOREIGN_KEY_CHECKS=0;");
                        stmt2.executeUpdate("ALTER TABLE region DISABLE KEYS;");
                        stmt2.executeUpdate("DELETE FROM region where code =" + valores + ";");
                        stmt2.executeUpdate("ALTER TABLE region ENABLE KEYS;");
                        stmt2.executeUpdate("SET FOREIGN_KEY_CHECKS=1;");
                        stmt3.execute("Update TB_Bitacora set Copied = 1 where nombretabla =" + valores);
                    } else if (nombretable.equals("PC")) {
                        stmt2.executeUpdate("SET FOREIGN_KEY_CHECKS=0;");
                        stmt2.executeUpdate("ALTER TABLE region DISABLE KEYS;");
                        stmt2.executeUpdate("DELETE FROM region where code =" + valores + ";");
                        stmt2.executeUpdate("ALTER TABLE region ENABLE KEYS;");
                        stmt2.executeUpdate("SET FOREIGN_KEY_CHECKS=1;");
                        stmt3.execute("Update TB_Bitacora set Copied = 1 where nombretabla =" + valores);
                    } else if (nombretable.equals("Printer")) {
                        stmt2.executeUpdate("SET FOREIGN_KEY_CHECKS=0;");
                        stmt2.executeUpdate("ALTER TABLE region DISABLE KEYS;");
                        stmt2.executeUpdate("DELETE FROM region where code =" + valores + ";");
                        stmt2.executeUpdate("ALTER TABLE region ENABLE KEYS;");
                        stmt2.executeUpdate("SET FOREIGN_KEY_CHECKS=1;");
                        stmt3.execute("Update TB_Bitacora set Copied = 1 where nombretabla =" + valores);
                    } else if (nombretable.equals("Product")) {
                        stmt2.executeUpdate("SET FOREIGN_KEY_CHECKS=0;");
                        stmt2.executeUpdate("ALTER TABLE region DISABLE KEYS;");
                        stmt2.executeUpdate("DELETE FROM region where model  =" + valores + ";");
                        stmt2.executeUpdate("ALTER TABLE region ENABLE KEYS;");
                        stmt2.executeUpdate("SET FOREIGN_KEY_CHECKS=1;");
                        stmt3.execute("Update TB_Bitacora set Copied = 1 where nombretabla =" + valores);
                    }

                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Migracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Migracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Migracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Migracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Migracion().setVisible(true);
            }
        });
    }

    public static Connection getMysqlConnection() {
        connectionmysql = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connectionmysql = DriverManager.getConnection("jdbc:mysql://localhost:3305/computer", "root", "deathnote114771");
            Statement stmt = connectionmysql.createStatement();
            /*rs = stmt.executeQuery("select * from categories");
            while (rs.next()) {
                System.out.println(rs.getInt(1) + rs.getString(2) + rs.getString(3) + rs.getInt(4));
            }*/
            //connection.close();
        } catch (Exception ex) {
            System.out.println(ex);
        }
        return connectionmysql;
    }

    public static Connection getSQLSERVERConnection() {
        connectionsqlserver = null;
        String dbname = "computer";
        String user = "Carlos114771";
        String pass = "deathnote114771";

        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionBD = "jdbc:sqlserver://localhost;databaseName="
                    + dbname + ";user=" + user + ";password=" + pass + ";";
            connectionsqlserver = DriverManager.getConnection(connectionBD);
        } catch (ClassNotFoundException e) {
            System.out.println("Error: " + e.getMessage());
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
        return connectionsqlserver;
    }

    static Connection conectSQL, connectMySQL;
    static int tablaSeleccionada = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_Replicar;
    private javax.swing.JButton btn_desReplicar;
    private javax.swing.JButton btn_probarDestino;
    private javax.swing.JButton btn_probarOrigen;
    private javax.swing.JCheckBox cb_LaptopSERVER;
    private javax.swing.JCheckBox cb_PCMYSQL;
    private javax.swing.JCheckBox cb_PCSERVER;
    private javax.swing.JCheckBox cb_laptopMYSQL;
    private javax.swing.JCheckBox cb_printerMYSQL;
    private javax.swing.JCheckBox cb_printerSERVER;
    private javax.swing.JCheckBox cb_productMYSQL;
    private javax.swing.JCheckBox cb_productSERVER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPasswordField pf_passwordDestino;
    private javax.swing.JPasswordField pf_passwordOrigen;
    private javax.swing.JTextField tf_baseDatosDestino;
    private javax.swing.JTextField tf_baseDatosOrigen;
    private javax.swing.JTextField tf_instanciaDestino;
    private javax.swing.JTextField tf_instanciaOrigen;
    private javax.swing.JTextField tf_puertoDestino;
    private javax.swing.JTextField tf_puertoOrigen;
    private javax.swing.JTextField tf_usuarioDestino;
    private javax.swing.JTextField tf_usuarioOrigen;
    // End of variables declaration//GEN-END:variables
}
